--PROYECTO BINAES

CREATE DATABASE BINAES

USE BINAES

CREATE TABLE EJEMPLAR(
	id INT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	imagen VARCHAR(50) NOT NULL,
	fecha_publicacion DATETIME NOT NULL,
	disponibilidad INT NOT NULL,
	id_coleccion INT NOT NULL,
	id_idioma INT NOT NULL,
	id_editorial INT NOT NULL,
	id_formato INT NOT NULL,
	id_autor INT NOT NULL
);

CREATE TABLE EDITORIAL(
	id INT PRIMARY KEY,
	editorial VARCHAR(50) NOT NULL
);

CREATE TABLE FORMATO_EJEMPLAR(
	id INT PRIMARY KEY,
	formato VARCHAR(10) NOT NULL
);

CREATE TABLE IDIOMA_EJEMPLAR(
	id INT PRIMARY KEY,
	idioma CHAR(20) NOT NULL
);

CREATE TABLE NOMBRE_ETIQUETA(
	id INT PRIMARY KEY,
	nombre VARCHAR(4) NOT NULL
);

CREATE TABLE ETIQUETA(
	id INT PRIMARY KEY,
	etiqueta VARCHAR(50) NOT NULL,
	id_nombre_etiqueta INT NOT NULL,
	id_ejemplar INT NOT NULL
);

CREATE TABLE GENERO_COLECCION(
	id INT PRIMARY KEY,
	formato VARCHAR(20) NOT NULL
);

CREATE TABLE TIPO_COLECCION(
	id INT PRIMARY KEY,
	formato VARCHAR(30) NOT NULL
);

CREATE TABLE COLECCION(
	id INT PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	id_tipo INT NOT NULL,
	id_genero INT NOT NULL
);

CREATE TABLE AUTOR(
	id INT PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL
);

CREATE TABLE AUTORXEJEMPLAR(
    id_autor INT NOT NULL,
    id_ejemplar INT NOT NULL
);

CREATE TABLE PALABRA_CLAVE(
	id INT PRIMARY KEY,
	palabra VARCHAR(50) NOT NULL,
	id_ejemplar INT NOT NULL
);

CREATE TABLE RESERVA(
	id INT PRIMARY KEY,
	fecha_reserva DATETIME NOT NULL,
	fecha_prestamo DATETIME NULL,
	fecha_devolucion DATETIME NULL,
	id_ejemplar INT NOT NULL,
	id_usuario INT NOT NULL
);

CREATE TABLE PRESTAMO(
	id INT PRIMARY KEY,
	fecha_prestamo DATETIME NOT NULL,
	fecha_devolucion DATETIME NULL,
	id_ejemplar INT NOT NULL,
	id_usuario INT NOT NULL
);

CREATE TABLE ROL(
	id CHAR(6) PRIMARY KEY,
    nombre CHAR(20)
);

CREATE TABLE OCUPACION_USUARIO(
	id INT PRIMARY KEY,
	ocupacion VARCHAR(30) NOT NULL
);

CREATE TABLE USUARIO(
	id INT PRIMARY KEY,
	institucion VARCHAR(50) NOT NULL,
	telefono CHAR(12) NOT NULL,
	--fotografia
	correo_electronico VARCHAR(50) NOT NULL,
	id_rol INT NOT NULL,
	id_ocupacion INT NOT NULL
);

CREATE TABLE AREA(
	id INT PRIMARY KEY,
	nombre VARCHAR(40) NOT NULL,
	descripcion VARCHAR(280) NOT NULL,
	horario_abierto VARCHAR(20) NOT NULL,
	nombre_responsable VARCHAR(50) NOT NULL
);

CREATE TABLE INGRESO(
	id INT PRIMARY KEY,
	fecha_entrada DATETIME NOT NULL,
	fecha_salida DATETIME NULL,
	id_area INT NOT NULL,
	id_usuario INT NOT NULL
);

CREATE TABLE EVENTO(
	id INT PRIMARY KEY,
	titulo VARCHAR(50) NOT NULL,
    Imagen VARCHAR(100) NOT NULL,
	fecha_inicio DATETIME NOT NULL,
	numero_asistentes INT NOT NULL,
	id_area INT NOT NULL
);

CREATE TABLE OBJETIVO_EVENTO(
	id INT PRIMARY KEY,
	objetivo VARCHAR(150) NOT NULL,
	id_evento INT NOT NULL
);
GO

--Creacion de llaves foraneas
ALTER TABLE ETIQUETA ADD CONSTRAINT fk_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES EJEMPLAR(id);
ALTER TABLE COLECCION ADD CONSTRAINT fk_coleccion_genero FOREIGN KEY (id_genero) REFERENCES GENERO_COLECCION(id);
ALTER TABLE COLECCION ADD CONSTRAINT fk_tipo_coleccion FOREIGN KEY (id_tipo) REFERENCES TIPO_COLECCION(id);
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_coleccion_ejemplar FOREIGN KEY (id_coleccion) REFERENCES COLECCION (id);
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_idioma_ejemplar FOREIGN KEY (id_idioma) REFERENCES IDIOMA_EJEMPLAR(id);
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_editorial_ejempalr FOREIGN KEY (id_editorial) REFERENCES EDITORIAL (id);
ALTER TABLE EJEMPLAR ADD CONSTRAINT fk_formato_ejemplar FOREIGN KEY (id_formato) REFERENCES FORMATO (id);
ALTER TABLE PRESTAMO ADD CONSTRAINT fk_ejemplar_prestamo FOREIGN KEY (id_ejemplar) REFERENCES EJEMPLAR (id);
ALTER TABLE PRESTAMO ADD CONSTRAINT fk_usuario_prestamo FOREIGN KEY (id_usuario) REFERENCES USUARIO(id);
ALTER TABLE AUTORXEJEMPLAR ADD CONSTRAINT fk_autorxejemplar PRIMARY KEY (id_autor, id_ejemplar);
ALTER TABLE PALABRA_CLAVE ADD CONSTRAINT fk_ejemplar_palabra_clave FOREIGN KEY (id_ejemplar) REFERENCES EJEMPLAR(id);
ALTER TABLE RESERVA ADD CONSTRAINT fk_reserva_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES EJEMPLAR(id);
ALTER TABLE RESERVA ADD CONSTRAINT fk_usuario_reserva FOREIGN KEY (id_usuario) REFERENCES USUARIO(id);
ALTER TABLE USUARIO ADD CONSTRAINT fk_rol_usuario FOREIGN KEY (id_rol) REFERENCES ROL(id);
ALTER TABLE USUARIO ADD CONSTRAINT fk_ocupacion_usuario FOREIGN KEY (id_ocupacion) REFERENCES OCUPACION_USUARIO(id);
ALTER TABLE INGRESO ADD CONSTRAINT fk_usuario_ingreso FOREIGN KEY (id_usuario) REFERENCES USUARIO(id);
ALTER TABLE EVENTO ADD CONSTRAINT fk_area_evento FOREIGN KEY (id_area) REFERENCES AREA(id);
ALTER TABLE OBJETIVO_EVENTO ADD CONSTRAINT fk_objetivo_evento FOREIGN KEY (id_evento) REFERENCES EVENTO(id);
GO


















