CREATE OR ALTER FUNCTION GET_EJEMPLARES_IN_PALABRA_CLAVE(@palabras_clave VARCHAR(255))
RETURNS TABLE
AS RETURN (
    SELECT P.id_ejemplar FROM PALABRA_CLAVE P
    WHERE P.palabra IN(SELECT * FROM STRING_SPLIT(@palabras_clave, ','))
);